### ISSUE TITLE
Update CONTRIBUTING to point to gh-pages branch

### ISSUE THREAD

**Issue by emhart** [datacarpentry/sql-ecology#20]
In the CONTRIBUTING.md (https://github.com/datacarpentry/sql-ecology/blame/gh-pages/CONTRIBUTING.md#L31) step 5 says to issue PR to the `master` branch.  However when I look at the repo I see only `gh-pages`.  Should the CONTRIBUTING file be updated?

**Comment by lwasser** [comment]
I'll let @ethanwhite answer as well as he's seems to maintain this repo BUT it was decided recently to make all DC repos gh-pages only. @fmichonneau  just went through and converted them all. 
More here: 
https://github.com/datacarpentry/lesson-template/issues/1

**Comment by ethanwhite** [comment]
Yes, the CONTRIBUTING file should be updated and PRs should be against `gh-pages`. Thanks!

**Comment by ethanwhite** [comment]
Fixed in 6a0ea1ebe5b94e78e53c964f881590ae75c670a6. Thanks @emhart!
