### ISSUE TITLE
Split material into lessons?

### ISSUE THREAD

**Issue by apawlik** [datacarpentry/sql-ecology#28]
Currently all material is on one file. Most modules are split into smaller chunks - each one is a separate lesson. It may be good to do the same with SQL (?). This should also be combined with adding more examples and some more material / revising wording to expand the lessons.

**Comment by ethanwhite** [comment]
No objections here.

**Comment by tracykteal** [comment]
Yes, good idea to put it into modules.

**Comment by tracykteal** [comment]
It can follow the standard format of 00-intro.md and then the following sections where there's a concept and then exercises on that concept in each module.

**Comment by ethanwhite** [comment]
Closed by #34.
