### ISSUE TITLE
More detail on section about Views

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/sql-ecology#36]
@ethanwhite mentioned that Views are the standard way to save queries. This, along with how to export csv files of the data from a query are already mentioned in the current lesson. 

Could we add some more detail to the Views section though, to explain what a view is, how to create it and how to use it again later? Something like 'the anatomy of a view'? I think both instructors and learners would benefit for some more detail in that section. 

A few points I've run across in particular:
- you can select Create View and it pops up a window. Do you copy and paste a query in there, or is it possible to create a View from a query you just ran?
- Export View brings up an Export Wizard. You can export the CSV which makes sense that you're exporting the data that's the result of the current query. There's also the option to export the SQL and a couple buttons. Would you ever want to export the SQL? If you do, what buttons do you select?
- Once you create a View, I found that I could see what query I ran by clicking on the 'Structure' tab, but that wasn't intuitive. I would have expected it to appear in the 'Execute SQL' tab.

**Comment by ethanwhite** [comment]
This information should replace the current information on `Saving a Query`. I'm not actually sure when that current information got included, but it seems very specific to SQLite as opposed to Views which are a standard way to do this.

If anyone has any objections to making this change please let us know.

**Comment by tpoisot** [comment]
Working on it at the moment. I'll submit a PR when I'm done with a draft.
