### ISSUE TITLE
potentially change structure of JOIN statement

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/sql-ecology#38]
Our current JOIN statement is

SELECT *
FROM surveys
JOIN species ON surveys.species_id = species.species_id

When I restructured it as 

SELECT *
FROM surveys JOIN species 
ON surveys.species_id = species.species_id

participants suggested it made more sense to see on the same line the two tables that were being joined. I don't know if this conforms to standard formatting or if it would help beyond this one case, but just a thought.

**Comment by tracykteal** [comment]
I'm generally happy to work on any of these issues I just put in. I just want to wait until the merge of the split out lesson with the proper templates before making new PRs.

**Comment by hlapp** [comment]
Line breaks are ignored in SQL so technically it doesn't matter on which line the JOIN is. I suspect it was on its own line as a remnant from having multiple JOINs, which, however, in reality is the much more common case. But I can see how in the case of a single JOIN it's more intuitive to visually "bind" it to the first FROM table.

**Comment by ethanwhite** [comment]
A little looking around suggests that your version is certainly in the realm of standard structure and I can see how it would be easier to learn, so let's go for it. I'll submit a PR in a second.
