### ISSUE TITLE
Improve one clause per line code block and discussion

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/sql-ecology#51]
There are currently two versions of the same SQL statement. The idea is to demonstrate that a better way of writing longer queries is one clause per line, but this isn't discussed in the notes. The code block should be split into two separate code blocks and language about the one clause per line approach added.

**Comment by tpoisot** [comment]
I might have removed this in one of the PR. I'll add a note somewhere saying that queries can be on a single line, but are easier to read / edit if they are split.
