### ISSUE TITLE
Markdown headers

### ISSUE THREAD

**Issue by tpoisot** [datacarpentry/sql-ecology#71]
Is there a rationale for the markdown headers? It seems to be a mix of `#` and `-`, and I'm just a little bit obsessive about these things.

Should we decide on a standard, or is there one in place that is convoluted to the point of eluding me?

**Comment by fmichonneau** [comment]
Use # wherever you make edits. The - are mostly legacy. This style should
already be included in the CONTRIBUTING.

**Comment by tpoisot** [comment]
Got it.
